### ISSUE TITLE
Update dependency org.scalameta:scalameta

### ISSUE THREAD

**Issue by 47degfreestyle** [frees-io/freestyle-rpc#111]
Actual version: 1.8.0
 Patch: -
 Minor: -
 Major: 3.2.0

**Comment by L-Lavigne** [comment]
Implemented in https://github.com/47deg/sbt-org-policies/pull/1008.

**Comment by L-Lavigne** [comment]
We have decided not to update scalameta and eventually get rid of it instead; the patch above disables dependency checking for it instead.
