### ISSUE TITLE
Docs - Split into different sections

### ISSUE THREAD

**Issue by juanpedromoreno** [frees-io/freestyle-rpc#176]
Currently, all the `frees-rpc` documentation is concentred in http://frees.io/docs/rpc, in a single [markdown document](https://github.com/frees-io/freestyle-rpc/blob/4eff4f7/docs/src/main/tut/README.md). It would be handy splitting it into different sections under http://frees.io/docs/rpc. For example:

* Quickstart
* Core Concepts
* IDL Generation
* Annotations
* Patterns
* Streaming
* Metrics Reporting
* SSL/TLS
* References
* etc.

**Comment by eperinan** [comment]
I have just created the new structure in the left bar with the new `microservices` section outside of Libraries. I put off this section in that place, as a consequence of following the same design.

Does it make sense to you?

<img width="248" alt="captura de pantalla 2018-03-06 a las 1 30 04" src="https://user-images.githubusercontent.com/3660921/37007540-09a7ffe8-20de-11e8-8a39-95612f3cbd72.png">

**Comment by juanpedromoreno** [comment]
LGTM, thanks @eperinan
