### ISSUE TITLE
Docs - Compression Support

### ISSUE THREAD

**Issue by juanpedromoreno** [frees-io/freestyle-rpc#179]
We need to write documentation explaining how to use compression (GZip) in both ends (server and client).

PR bringing support: https://github.com/frees-io/freestyle-rpc/pull/161

**Comment by fedefernandez** [comment]
This is how the compression is enabled.

**In Server**

Adding `Gzip` to the `@rpc` method annotation
https://github.com/frees-io/freestyle-rpc/blob/47552a3405cb49c48e7937c4712fee1f36ecdf9b/modules/server/src/test/scala/protocol/Utils.scala#L47
https://github.com/frees-io/freestyle-rpc/blob/923c99275066fc0ded0c272d2c884eaa3766faa1/modules/server/src/test/scala/fs2/Utils.scala#L34

**In Client**

It was already supported by passing the `CallOptions` in the *channel* builder:
Something like this (I think we don't have any test):
```scala
RPCService.client[IO](
  ChannelForAddress("localhost", 8080),
  options = CallOptions.DEFAULT.withCompression("gzip"))
```
