### ISSUE TITLE
Freestyle-RPC Benchmarks

### ISSUE THREAD

**Issue by juanpedromoreno** [frees-io/freestyle-rpc#228]
We need to create a new module for benchmarking. https://github.com/47deg/metrifier can be used as a reference, however, we need to include all the different combinations:

* Avro, AvroWithSchema, ProtocolBuffers, etc.
* Interceptors (server, client)
* Any kind combination.

As part of this story, it would be really handy to measure and establish minimum throughput values as threshold. Hence, in CI, we might a have a new stage in the pipeline that might fail if new features/modifications included in the commits are not reaching these thresholds.

**Comment by L-Lavigne** [comment]
Metrifier conversion WIP is on branch https://github.com/47deg/metrifier/commits/UpgradeToNewHotness.
