### ISSUE TITLE
Random test failure - Client bidirectional Streaming

### ISSUE THREAD

**Issue by AdrianRaFo** [frees-io/freestyle-rpc#237]
A random failure on the test :

"frees-rpc client should be able to run client bi-directional streaming services"

with the error:
```
List() was not equal to 
List(E(A(100,200),foo3), E(A(1000,2000),foo4))
```

is ignored on Travis for now

**Comment by fedefernandez** [comment]
Possible duplicated by #164

**Comment by L-Lavigne** [comment]
Closing as duplicate of #164 since those only seem to happen for FS2 bidi tests; let's (re-)open as a separate issue if we see it happening with Monix and/or non-bidi tests.

(Folks getting notifications for the testing issues: sorry to have gotten your hopes up)
