### ISSUE TITLE
Random test failure - Client fs2.Stream bidirectional Streaming

### ISSUE THREAD

**Issue by AdrianRaFo** [frees-io/freestyle-rpc#242]
A random failure on the test :

"frees-rpc client with fs2.Stream as streaming implementation should be able to run client bidirectional streaming services"

with the error:

```
List() was not equal to 
List(E(A(100,200),foo3), E(A(1000,2000),foo4))
```

is ignored on Travis for now

**Comment by fedefernandez** [comment]
Possible duplicated by #164

**Comment by AdrianRaFo** [comment]
Right
