### ISSUE TITLE
Support for more message field types

### ISSUE THREAD

**Issue by TimWSpence** [frees-io/freestyle-rpc#265]
Is it possible to support additional parameter types in messages? Consider for example
`case class Id(value: UUID)`

For the underlying pbDirect serialization/deserialization, I can define something like this:
`implicit val uuidFormat: PBFormat[UUID] = PBFormat[String].imap(UUID.fromString)(_.toString)`

However, I don't see a way to similarly hook into freestyle-rpc. I get
`could not find implicit value for parameter e: io.grpc.MethodDescriptor.Marshaller[Key]` errors, which I'm pretty sure are because UUID is not a primitive type in protobufs. However, we should be able to provide an appropriate PBFormat and use UUID in our domain classes.

**Comment by TimWSpence** [comment]
OK, I found the answer - freestyle-rpc provides an implicit conversion from a `PBFormat` to a `Marshaller`. Maybe this could be made clearer in the documentation?

**Comment by juanpedromoreno** [comment]
You are correct, sorry for the late reply. In this file, you can see the currently supported marshallers for both Protobuf and Avro: https://github.com/frees-io/freestyle-rpc/blob/32880c6d927f0bb79416810a5dfd285c1711c269/modules/internal/src/main/scala/encoders.scala

Any kind of improvement, including the documentation, is very welcome :) . Thanks!

**Comment by TimWSpence** [comment]
OK cool, I'll try to find some time to write it up :)

**Comment by juanpedromoreno** [comment]
@TimWSpence Just a heads up. Now, `frees-rpc` supports more types: https://github.com/frees-io/freestyle-rpc/pull/374, including custom ones by the user. Please, feel free to re-open this in case you find any issues. Thanks!
