### ISSUE TITLE
Migrate IDL Generation

### ISSUE THREAD

**Issue by L-Lavigne** [frees-io/freestyle-rpc#298]
The `idlGen` sbt plugin leverages the macro-parsed `@service` definitions. As those get converted in #291, we'll need to migrate the plugin as well.

One possibility to explore is to _not_ use macros for the plugin, since it only reads the definitions and doesn't modify them or generate any code. Using some reflection-based API could be advantageous if it gives us more flexibility in handling types whose declarations deviate from the narrow range of textual statements we support (see https://github.com/frees-io/sbt-freestyle-protogen/issues/19 from the old plugin project).

**Comment by pepegar** [comment]
I would prefer sticking to macros instead of runtime reflection.

I'm afraid of runtime reflection for example because of type
erasure.

Also, if it's possible to do it at compile time via macros, I prefer
it :)

**Comment by pepegar** [comment]
A bit of progress on this one. I haven't found any way of doing this at compile time (and after thinking a bit about it, i think it doesn't make sense), so I'm implementing it via the scala compiler directly, using the reflect APIs.

Progress being done in #326

**Comment by pepegar** [comment]
Done in #326!
