### ISSUE TITLE
Spike: Add some test cases for model evolutions

### ISSUE THREAD

**Issue by rafaparadela** [frees-io/freestyle-rpc#331]
This ticket should provide some unit tests to cover the interoperability for old clients that keep pushing evolved services using legacy schemas. Some of the scenarios we want to cover:

- Add new non-optional field in the request
- Add new optional field in the request
- Add item to a coproduct in the request
- Remove item to a coproduct in the request
- Change type of an existing field in the request
- Rename field in the request
- Remove field in the request
- Add new non-optional field in the response
- Add new optional field in the response
- Add item to a coproduct in the response
- Remove item to a coproduct in the response
- Change type of an existing field in the response
- Rename field in the response
- Remove field in the response

**Comment by diesalbla** [comment]
For each of those cases, we have to consider what happens when the change affects the Request and when it affects the Response of the method.

**Comment by rafaparadela** [comment]
True. I'm focused on the evolution of the requests at the moment.

**Comment by diesalbla** [comment]
Another dimension to consider is what happens when the client uses, or does not use, what has been  added, modified, or removed. Be that a field from a case class, or a case class from the coproduct.

**Comment by juanpedromoreno** [comment]
Please, @rafaparadela could you use the https://github.com/frees-io/freestyle-rpc/tree/release/0.14.0 branch? It'd be really appreciated. Thanks.

**Comment by rafaparadela** [comment]
# Conclusions:

### Cases:

- **A**: Add new non-optional field in the request
- **B**: Add new optional field in the request
- **C**: Add item to a coproduct in the request
- **D**: Remove item to a coproduct in the request
- **E**: Change type of an existing field in the request
- **F**: Rename field in the request
- **G**: Remove field in the request
- **H**: Add new non-optional field in the response
- **I**: Add new optional field in the response
- **J**: Add item to a coproduct in the response
- **K**: Remove item to a coproduct in the response
- **L**: Change type of an existing field in the response
- **M**: Rename field in the response
- **N**: Remove field in the response



### A: Add new non-optional field in the request
Request: Provide default value to the new field.

```scala
case class Request(a: String, b: Int)
case class NewRequest(a: String, b: Int, c: Boolean = true)
```

### B: Add new optional field in the request
Request: This is just another case of the previous scenario. The solutions could be to provide a default value, that presumably could be None/null.

### C: Add item to a coproduct in the request
Request: No action required

```scala
case class Request(a: Int :+: String :+: CNil)
case class NewRequest(a: Int :+: String :+: Boolean :+: CNil)
```

### D: Remove item to a coproduct in the request
Request: The only way to deal with this situation is considering this as a change of type, see next case.

```scala
case class Request(a: Int :+: String :+: CNil)
case class NewRequest(b: String :+: CNil = Coproduct[String :+: CNil](""))
```

### E: Change type of an existing field in the request
Request: It's is impossible to deal with a type swapping if we maintain the same name of the field. So the solution is considering this replacement as a combination of removing the old field/type, and adding a new field with the new type with a default value.

```scala
case class Request(a: String, b: Int)
case class NewRequest(a: String, c: Boolean = true)
```

### F: Rename field in the request
Request: Renaming a field is a particular case of creating a field with the new name and default value, and remove the old one, that will be ignored if old clients pass it.

```scala
case class Request(a: String, b: Int)
case class NewRequest(a: String, c: Int = 0)
```

### G: Remove field in the request
Request: No action required. But note that the value will be ignored when old clients include it in the request.

```scala
case class Request(a: String, b: Int)
case class NewRequest(a: String)
```

### H: Add new non-optional field in the response
Response: No action required. Old clients will ignore the value of the new field.

```scala
case class Response(a: String, b: Int)
case class NewResponse(a: String, b: Int, c: Boolean)
```

### I: Add new optional field in the response
Response: This is a just a particular case of the previous scenario.

### J: Add item to a coproduct in the response
Response: Obviously, it fails when the value is the new item. So the solution is providing a default value to the old coproduct and creating a new field with the new coproduct.

```scala
case class Response(a: Int :+: String :+: CNil)
case class NewResponse(
      a: Int :+: String :+: CNil = Coproduct[Int :+: String :+: CNil](0),
      b: Int :+: String :+: Boolean :+: CNil)
```

### K: Remove item to a coproduct in the response
Response: No action required.

```scala
case class Response(a: Int :+: String :+: CNil)
case class NewResponse(a: Int :+: CNil)
```

### L: Change type of an existing field in the response
Response: It requires to provide a default value to the previous type, and to create a new field with the new type.

```scala
case class Response(a: String, b: Int)
case class NewResponse(a: String, b: Int = 123, c: Boolean)
```

### M: Rename field in the response
Response: It requires to remain the previous name/type with a default value and to add a new field with the same type.

```scala
case class Response(a: String, b: Int)
case class NewResponse(a: String, b: Int = 123, c: Int)
```

### N: Remove field in the response
Response: This evolution should never happen. Only under the special case that the old response has a default value for the field we want to drop, then this operation is feasible, just removing the field in the new version of the response.

```scala
case class Response(a: String, b: Int = 123)
case class NewResponse(a: String)
```
