### ISSUE TITLE
Upgrade Avrohugger to RC12 for `Instant` type

### ISSUE THREAD

**Issue by zmccoy** [frees-io/freestyle-rpc#381]
When upgrading to Avrohugger 1.0.0-RC12 `timestamp_ms` in the AVDL will be turned into `java.time.Instant` rather than `LocalDateTime`.  To keep backwards compatibility between versions  I think we'd need to have both of those types be serialized/deserialized the same way.  

I'd love for any feedback.

**Comment by zmccoy** [comment]
I can start on the upgrade this weekend and see where I can get.

**Comment by fedefernandez** [comment]
Thanks @zmccoy. I agree with you, the encoders defined in freestyle-rpc for `LocalDateTime` encode the values with the Timestamp millisecond precision approach.

https://avro.apache.org/docs/1.8.2/spec.html#Timestamp+%28millisecond+precision%29
